pizza/urls.py
"""Define URL patterns for pizza."""

from django.conf.urls import url

from . import views

urlpatterns = [
    #Home page
    url(r'^$', views.index, name='index'),
    
    #show all available pizzas.
    url(r'^pizza/$', views.pizzas, name='pizza'),
    
    # Details page for each pizza
    url(r'^pizzas/(?P<pizza_id>\d+)/$', views.pizza, name='pizza'),
]

pizzas/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('pizza.urls', namespace='pizzas')),
]

pizza/models.py
from django.db import models

class Pizza(models.Model):
    """The name of different kinds of Pizzas"""
    name = models.CharField(max_length=200)
    #date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        """Return a string representation of the model."""
        return self.name
        
        
class Topping(models.Model):
    """Give a description of the Pizza"""
    pizza = models.ForeignKey(Pizza)
    name = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'toppings'
    
    def __str__(self):
        """Return a string representation of the model."""
        return self.name[:50] + "..."

pizza/views.py
from django.shortcuts import render

from .models import Pizza


def index(request):
    """The homepage for Pizzeria"""
    return render(request, 'pizzas/index.html')
    
    
def pizzas(request):
    """Show all Pizzas."""
    pizzas =  Pizza.objects.order_by()
    context = {'pizzas': pizzas}
    return render(request, 'pizzas/pizza.html', context)
    
    
def pizza(request, pizza_id):
    """Show a single pizza and its toppings"""
    pizza = Pizza.objects.get(id=pizza_id)
    toppings = pizza.topping_set.order_by('-date_added')
    context = {'pizza': pizza, 'toppings': toppings}
    return render(request, 'pizzas/pizzs.html', context)

pizza/templates/pizzas/base.html
<p>
  <a href="{% url 'pizzas:index' %}">Pizzas</a> - 
  <a href="{% url 'pizzas:pizza' %}">Pizza</a>
</p>


{% block content %}{% endblock content %}

pizza/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}
  <p>Your Number source for delicious Pizzas</p>

{% endblock content %}

pizza/templates/pizzas/pizza.html
{% extends "pizzas/base.html" %}

{% block content %}

  <p>Pizza</p>
  
  <ul>
    {% for pizza in pizzas %}
      <li>
        <a href="{% url 'pizzas:pizza' pizza.id %}">{{ pizza }}</a>
      </li>
    {% empty %}
      <li>No pizza have available yet.</li>
    {% endfor %}
  </ul>
  
{% endblock content %}

pizza/templates/pizzas/pizzs.html
{% extends 'pizzas/base.html' %}

{% block content %}

  <p>Pizza: {{ pizza }}</p>

  <p>Toppings:</P>
  <ul>
  {% for topping in toppings %}
    <li>
      <p>{{ topping.date_added|date:'M d, Y H:i' }}</p>
      <p>{{ topping.name|linebreaks }}</p>
    </P>
  {% empty %}
    <li>
      There are no toppings available yet for this pizza.
    </li>
  {% endfor %}
  </ul>
  
  
{% endblock content %}